site:
  title: devonfw
  start_page: dotnet::index.adoc 
  url: https://devonfw.com
content:
  sources: 
  - url: .
    start_path: .
ui: 
  bundle:
    url: https://github.com/devonfw/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
urls: 
  latest_version_segment: current
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
asciidoc:
  extensions:
  - "./extensions/tabs.js" 
  - "asciidoctor-external-callout"
  - asciidoctor-kroki
